baseURL = "https://blog.little-data.top/"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "Little-data"
theme = "fluency"
enableRobotsTXT = true
summaryLength = 100
pygmentsUseClasses = true
pygmentsCodefences = true
hasCJKLanguage = true
enableEmoji = true
ignoreErrors = [
  "error-remote-getjson",
  "error-missing-instagram-accesstoken"
]

[minify]
disableSVG = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Little-data"
description = "Music the best"
mainSections = [ "posts" ]
extraMeta = [
"<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="/img/by-nc-sa-88x31.png" /></a>本文采用<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。"
]
disableSocialShare = true
disableIndexSummary = false
disableAnchorHeading = false
disableBreadcrumb = false
disableComment = false
disableCommentByType = [ "page", "postsdis" ]
thirdPartyComment = [
"<div id="tcomment"></div>
<script src="https://cdn.staticfile.org/twikoo/1.6.16/twikoo.all.min.js"></script>
<script>
 twikoo.init({
envId: 'https://lite-twikoo.zeabur.app/', // 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
el: '#tcomment', // 容器元素
 // region: 'ap-guangzhou', // 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
 // path: location.pathname, // 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
 // lang: 'zh-CN', // 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js
 })
</script>"
]
mathRender = true

  [params.pageSize]
  index = 5
  list = 10
  archives = 20

[[menu.main]]
identifier = "posts"
name = "文章"
url = "posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "标签"
url = "tags/"
weight = 2

[[menu.main]]
identifier = "archives"
name = "存档"
url = "archives/"
weight = 3

[[menu.main]]
identifier = "about"
name = "关于"
url = "about/"
weight = 4

[[menu.main]]
identifier = "website"
name = "留言板"
url = "lyb.html"
weight = 5

[[menu.main]]
identifier = "webc"
name = "网站集合"
url = "https://mos.little-data.top/m/6"
weight = 6

[[menu.footer]]
identifier = "github"
url = "https://github.com/little-data"
name = "Github"

[[menu.footer]]
identifier = "bilibili"
url = "https://space.bilibili.com/357695126"
name = "Bilibili主页"

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = false
disable = true
respectDoNotTrack = false
useSessionStorage = false

[privacy.instagram]
disable = true
simple = false

[privacy.twitter]
disable = true
enableDNT = false
simple = false

[privacy.vimeo]
disable = true
enableDNT = false
simple = false

[privacy.youtube]
disable = true
privacyEnhanced = false
