baseURL= "https://blog.little-data.top/"
languageCode= "zh-cn"
defaultContentLanguage= "zh"
title=" Little-data"
theme= "fluency"
enableRobotsTXT= true
summaryLength= 100 # Configure how long the post summary should be on the homepage.
pygmentsUseClasses= true # enable theme-defined highlight style
pygmentsCodefences= true
hasCJKLanguage= true
enableEmoji= true

[ignoreErrors]
  = error-remote-getjson
  = error-missing-instagram-accesstoken

# googleAnalytics= UA-XXXXXXXXX-X
# disqusShortName= hugo

[minify]
  disableSVG= true

[markup]
  [goldmark]
    [renderer]
      unsafe= true

[taxonomies]
  category= categories
  tag= tags

# permalinks=
#  posts= :section/:slug

[params]
  author= Little-data
  description= "Music the best"
  # copyright: "© 2021 &nbsp;<a href='https://github.com/wayjam/hugo-theme-fluency'>Hugo Theme Fluency</a>"

  # main section will be listed at index page
[mainSections]
    = posts

  # set number of post of specify type of content
  [pageSize]
    index= 5
    list= 10
    archives= 20

  # extra info below post
  [extraMeta] |
     <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="/img/by-nc-sa-88x31.png" /></a>本文采用<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。
  #   <p>another line</p>

  disableSocialShare= true
  disableIndexSummary= false
  disableAnchorHeading= false
  disableBreadcrumb= false

  # comment
  disableComment= false
  [disableCommentByType]
    = page
    = postsdis
  [thirdPartyComment]

    <div id="tcomment"></div>
    <script src="https://cdn.staticfile.org/twikoo/1.6.16/twikoo.all.min.js"></script>
    <script>
     twikoo.init({
    envId: 'https://lite-twikoo.zeabur.app/', // 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
    el: '#tcomment', // 容器元素
     // region: 'ap-guangzhou', // 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
     // path: location.pathname, // 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
     // lang: 'zh-CN', // 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js
     })
    </script>

  # refer to https://gohugo.io/content-management/formats/
  mathRender= true

  # customScript: |
  #   <script>console.log('hello world')</script>

[menu]
  [main]
     identifier= posts
      name= 文章
      url= posts/
      weight= 1
     identifier= tags
      name= 标签
      url= tags/
      weight= 2
     identifier= archives
      name= 存档
      url= archives/
      weight= 3
     identifier= about
      name= 关于
      url= about/
      weight= 4
     identifier= website
      name= 留言板
      url= lyb.html
      weight= 5
     identifier= webc
      name= 网站集合
      url= https://mos.little-data.top/m/6
      weight= 6

  [footer]
     identifier= github
      url= "https://github.com/little-data"
      name= Github
     identifier= bilibili
      url= "https://space.bilibili.com/357695126"
      name= Bilibili主页

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [disqus]
    disable= true
  [googleAnalytics]
    anonymizeIP= false
    disable= true
    respectDoNotTrack= false
    useSessionStorage= false
  [instagram]
    disable= true
    simple= false
  [twitter]
    disable= true
    enableDNT= false
    simple= false
  [vimeo]
    disable= true
    enableDNT= false
    simple= false
  [youtube]
    disable= true
    privacyEnhanced= false
